repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: trailing-whitespace

- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
    - id: pyupgrade
      args: [--py37-plus]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.8
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
      exclude: \.md$
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

- repo: https://github.com/MarcoGorelli/madforhooks
  rev: 0.4.1
  hooks:
    - id: no-print-statements
      types: [python]
      exclude: |
            (?x)^
            |bond_pricer/model_builder.py$
            |bond_pricer/parser.py$

- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
    - id: absolufy-imports
      types: [python]

- repo: https://github.com/MarcoGorelli/madforhooks
  rev: 0.4.1
  hooks:
    - id: check-execution-order
      args: [--strict]
      exclude: |
            (?x)^
